---
title: "Lab 2: Introduction to RStudio"
author: "___"
date: "`r format(Sys.Date())`"
output: github_document
---

> INSTRUCTIONS: REMOVE THIS LINE AND REPLACE ____ WITH YOUR OWN TEXT

Welcome to my Lab 2 repository for Quantitative Biology BIOL 275 at MSUM.

## Lab objectives

The objectives of this lab are:

- ___
- ___

## Repository contents

The repository contains the following scripts:

- [calculator.R](calculator.R)
- [calculator.Rmd](calculator.Rmd)

## Instructions for knitting

Your actual README document must be a Markdown file. This one is an R Markdown file.

When you are done editing this document, click the Knit button in the Source Pane. RStudio will then convert this into a .md file and give you a preview in a separate window. Make sure everything looks okay and then close the preview window.

## R Markdown

This README is an R Markdown document (.Rmd), which means you can use markdown syntax and you can embed code chunks.

Here is a list of resources for helping you write R Markdown documents:

- In the Go to the **Help** menu and select **Markdown Quick Reference**
- [Basic Syntax](https://www.markdownguide.org/basic-syntax/) on the Markdown Guide website

## Session Info

Here is my session information:

```{r}
sessioninfo::session_info(c("tidyverse"))
```
